### PR TITLE
added sounds and added sounds to home page. tried to add sounds …

### PR DESCRIPTION
**Pull request by meierjl01**
…to battle but had some issues.

Initially, it played homer dying sound every time he loses points after being under 5 — changed that to play when he’s got 3 points or less. it’s still playing more than once, at this point though. If I do it when he dies, it plays into the game over screen opening up. I was gonna but a second sound on each attack but that seems overzealous. What do you guys think?

Also I'm having issues with getting the characters to have sounds play during the battle. Tried to put them in the “this” section with all the other gifs and images, but it didn’t work.I can’t write them into the function because it’ll depend on who the user is playing as. I guess we could do all sorts of if statements like if the character’s name is bart play his sound, if Lisa, play hers? It's also causing issues for the game-over page too. Thoughts?

### CODE REVIEW

**Comment by Drake-fish** [comment]
Hmmm that's interesting yeah we might need to put them in the object themselves so that way they could call it like they call the gifs and just play them when a click is made and in the timeouts maybe?

**Comment by meierjl01** [comment]
Yeah. I can do a merge so you guys can see what happens with each of them, if you want. That might be easier than just trying to imagine it.

**Comment by Drake-fish** [comment]
I'm ready to merge just need Jeff's consent

**Comment by Jeff-Lawlis08** [comment]
lets do it!

**Pull request merged**
